random_seed: 42
random_forest:
  n_estimators: 100
  max_depth: 7
  n_jobs: -1
  criterion: entropy
  max_features: 0.4
categorical_features:
  - workclass
  - education
  - marital-status
  - occupation
  - relationship
  - race
  - sex
  - native-country